---

- name: create mailcow.conf
  ansible.builtin.template:
    force: true
    src: mailcow.conf.j2
    dest: "{{ mailcow_install_path }}/active/mailcow.conf"
    owner: root
    group: root
    mode: "0640"
  register: mailcow_config
  notify:
    - validate config
  when:
    - not running_in_check_mode

- name: enable mailcow.conf
  ansible.builtin.file:
    src: "{{ mailcow_install_path }}/active/mailcow.conf"
    dest: "{{ mailcow_install_path }}/active/.env"
    state: link
    force: true
    follow: false
  when:
    - not running_in_check_mode

- name: copy tls certificates
  become: true
  bodsch.email.mailcow_tls_certificates:
    source:
      ssl_cert: "{{ mailcow_tls_certificate.source_files.cert | default(omit) }}"
      ssl_key: "{{ mailcow_tls_certificate.source_files.key | default(omit) }}"
      ssl_ca: "{{ mailcow_tls_certificate.source_files.ca | default(omit) }}"
      ssl_dh: "{{ mailcow_tls_certificate.source_files.dh | default(omit) }}"
    destination: "{{ mailcow_install_path }}/active/data/assets/ssl/"

...
