---

- name: create download directory
  when:
    - not mailcow_source == "git"
  become: false
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ mailcow_local_tmp_directory }}"
    state: directory
    mode: "0750"

- name: clone mailcow repository to ansible-host
  when:
    - mailcow_source == "git"
  block:
    - name: create temp directory
      ansible.builtin.file:
        path: "{{ mailcow_tmp_directory }}"
        state: directory
        mode: "0750"

    - name: clone git sources to temp directory
      become: true
      ansible.builtin.git:
        repo: "{{ mailcow_git.repository }}"
        version: "{{ mailcow_git.version | default('master') }}"
        dest: "{{ mailcow_tmp_directory }}"
        depth: 1
        update: true
        force: true
      no_log: true
      register: mailcow_repository_changed
