---

- name: include OS specific configuration
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian
        - "{{ ansible_os_family | lower }}.yml"
        # artixlinux
        - "{{ ansible_os_family | lower | replace(' ', '') }}.yml"
        # artixlinux-openrc
        - "{{ ansible_distribution | lower | replace(' ', '') }}-{{ ansible_service_mgr | lower }}.yml"
        - default.yml
      skip: true

- name: detect docker environment
  ansible.builtin.set_fact:
    is_docker_guest: "{{
      ansible_virtualization_role | default('host') == 'guest' and
      ansible_virtualization_type | default('none') == 'docker' }}"

- name: detect ansible check_mode
  bodsch.core.check_mode:
  register: _check_mode

- name: define running_in_check_mode
  ansible.builtin.set_fact:
    running_in_check_mode: '{{ _check_mode.check_mode }}'

- name: install dependencies
  ansible.builtin.package:
    name: "{{ mailcow_dependencies }}"
    state: present
  when:
    - mailcow_dependencies | default([]) | count > 0

...
