---

- name: enable service mailcow-config
  ansible.builtin.service:
    name: mailcow-config
    enabled: "{{ mailcow_service.enabled | default('true') | bool }}"
  tags:
    - mailcow
    - mailcow-service

- name: enable service mailcow-pull
  ansible.builtin.service:
    name: mailcow-pull
    enabled: "{{ mailcow_service.enabled | default('true') | bool }}"
  tags:
    - mailcow
    - mailcow-service

- name: start and enable service mailcow
  ansible.builtin.service:
    name: mailcow
    state: "{{ mailcow_service.state | default('started') }}"
    enabled: "{{ mailcow_service.enabled | default('true') | bool }}"
  tags:
    - mailcow
    - mailcow-service

...
