---

mailcow_tmp_directory: "/var/cache/ansible/mailcow/{{ mailcow_version }}"

mailcow_local_tmp_directory: "{{
  lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
  default(lookup('env', 'HOME') ~ '/.cache/ansible/mailcow', true) }}" # "/{{ mailcow_version }}"

# mailcow_download: false
# mailcow_download_directory: "/tmp/mailcow/mailcow-{{ mailcow_version }}"

systemd_lib_directory: /lib/systemd/system

...
