---

mailcow_service:
  state: stopped
  enabled: true

mailcow_bindings:
  http:
    address: "127.0.0.1"
    port: 8080
  https:
    address: "127.0.0.1"
    port: 8443


mailcow_api:
  allow_from:
    - "127.0.0.1"
    - "172.22.1."
  read_only: []
  key: "Npf5tufGC1r5Gx18d28wV6t7VM1wi6"

mailcow_maildir:
  home: ""
  gc_time: 60

...
